spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

lokoko:
  jwt:
    key: ${JWT_KEY}
    access:
      expiration: ${ACCESS_EXP}
      header: ${ACCESS_HEAD}
    refresh:
      expiration: ${REFRESH_EXP}
      header: ${REFRESH_HEAD}

line:
  client-id: ${LINE_CHANNEL_ID}
  client-secret: ${LINE_CHANNEL_SECRET}
  redirect-uri: ${LINE_CALLBACK_URL}
  base-url: ${LINE_BASE_URL}
  scope: ${LINE_SCOPE}

youtube:
  api-key: ${YOUTUBE_API_KEY}